name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make clean
      run: make clean

    - name: Install dependencies
      run: make

    - name: Run check
      run: ./runtests.exp mylog

